# Copyright (C) 2007-2019 Crafter Software Corporation. All Rights Reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    ports:
      - 9202:9200
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xss1024K -Xmx1G"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - elasticsearch_logs:/usr/share/elasticsearch/logs
    networks:
      craftercms:
        aliases:
          - delivery-elasticsearch   
  tomcat:
    image: craftercms/delivery_tomcat
    depends_on:
      - elasticsearch
    ports:
      - 9080:8080
    volumes:
      - crafter_data:/opt/crafter/data
      - crafter_logs:/opt/crafter/logs
      - crafter_temp:/opt/crafter/temp
      - crafter_authoring_data:/data/authoring
    environment:
      - ES_HOST=delivery-elasticsearch
      - ES_PORT=9200
    networks:
      craftercms:
        aliases:
          - delivery-tomcat
  deployer:
    image: craftercms/deployer
    depends_on:
      - elasticsearch
    ports:
      - 9192:9191
    volumes:
      - crafter_data:/opt/crafter/data
      - crafter_logs:/opt/crafter/logs
      - crafter_temp:/opt/crafter/temp
      - crafter_authoring_data:/data/authoring
    environment:
      - TOMCAT_HOST=delivery-tomcat
      - TOMCAT_HTTP_PORT=8080
      - ES_HOST=delivery-elasticsearch
      - ES_PORT=9200
    networks:
      craftercms:
        aliases:
          - delivery-deployer  
volumes:
  elasticsearch_data:
    name: crafter_delivery_data_elasticsearch
  elasticsearch_logs:
    name: crafter_delivery_logs_elasticsearch
  crafter_data:
    name: crafter_delivery_data
  crafter_logs:
    name: crafter_delivery_logs
  crafter_temp:
    name: crafter_delivery_temp
  crafter_authoring_data:
    external: true
networks:
  craftercms:
    name: craftercms