version: '3.7'
services:
  tomcat:
    image: craftercms/delivery_tomcat
    ports:
      - 9080:8080
    volumes:
      - crafter_data:/opt/crafter/data
      - crafter_logs:/opt/crafter/logs
      - crafter_temp:/opt/crafter/temp
      - ./config/engine/services-context.xml:/opt/crafter/bin/apache-tomcat/shared/classes/crafter/engine/extension/services-context.xml
      # Please specify a server-config.properties based on the provided server-config.properties.example (replace <> placeholders)
      - ./config/engine/server-config.properties:/opt/crafter/bin/apache-tomcat/shared/classes/crafter/engine/extension/server-config.properties
    networks:
      craftercms:
        aliases:
          - delivery-tomcat
volumes:
  crafter_data:
    name: crafter_serverless_s3_delivery_data
  crafter_logs:
    name: crafter_serverless_s3_delivery_logs
  crafter_temp:
    name: crafter_serverless_s3_delivery_temp
networks:
  craftercms:
    name: craftercms