version: '3.7'
services:
  mariadb:
    image: mariadb:10.1.37
    ports:
      - 33306:3306    
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes     
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      crafter:
        aliases:
          - authoring-mariadb
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    ports:
      - 9201:9200
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xss1024K -Xmx1G"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - elasticsearch_logs:/usr/share/elasticsearch/logs
    networks:
      crafter:
        aliases:
          - authoring-elasticsearch  
  tomcat:
    image: craftercms/authoring_tomcat
    depends_on:
      - mariadb
      - elasticsearch
      - deployer
    ports:
      - 8080:8080
    volumes:
      - crafter_data:/opt/crafter/data
      - crafter_logs:/opt/crafter/logs
      - crafter_temp:/opt/crafter/temp
    environment:
      - MARIADB_HOST=authoring-mariadb
      - MARIADB_PORT=3306      
      - DEPLOYER_HOST=authoring-deployer
      - DEPLOYER_PORT=9191
      - ES_HOST=authoring-elasticsearch
      - ES_PORT=9200
    networks:
      crafter:
        aliases:
          - authoring-tomcat
  deployer:
    image: craftercms/deployer
    depends_on:
      - elasticsearch  
    ports:
      - 9191:9191
    volumes:
      - crafter_data:/opt/crafter/data
      - crafter_logs:/opt/crafter/logs
      - crafter_temp:/opt/crafter/temp
    environment:
      - TOMCAT_HOST=authoring-tomcat
      - TOMCAT_HTTP_PORT=8080
      - ES_HOST=authoring-elasticsearch
      - ES_PORT=9200
    networks:
      crafter:
        aliases:
          - authoring-deployer
volumes:
  mariadb_data:
    name: crafter_authoring_data_mariadb
  elasticsearch_data:
    name: crafter_authoring_data_elasticsearch
  elasticsearch_logs:
    name: crafter_authoring_logs_elasticsearch
  crafter_data:
    name: crafter_authoring_data
  crafter_logs:
    name: crafter_authoring_logs
  crafter_temp:
    name: crafter_authoring_temp
networks:
  crafter:
    name: crafter